### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-ArturoAngonJose#2]
[Libreria Dll Calculadora.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-ArturoAngonJose/files/6339158/Libreria.Dll.Calculadora.pdf)

**Comment by Eva155** [comment]
Faltó la descripción y el índice; de igual forma no cumple con el número de figuras
Calificación: 18 puntos
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
